---
title: "dataCleaning_080620"
author: "Bernice Cheung"
date: "8/6/2020"
output: html_document
---

This script is used to corrected the stimuliDf file generated by the script 
```{r setup, include=FALSE}
library(readr)
library(readbulk)
```

```{r}
rawDf <- read_bulk(directory = "/Users/BerniceCheung/Documents/Bernice/socialContext_behavior/fMRI behavioral/rawData", extension = ".csv", fun = read.csv)
```

### Generate datasets for trait presentation and EV files

extract trials for actual trait presentation (exclude catch trials and repetitive trials in the output)

```{r}
# exclude rows with trialInRun = NaN (data before the presence of trait)
cleanedDf <- rawDf[is.na(rawDf$trialInRun) == F,]

# reorder the dataset based on subject ID
cleanedDf <- cleanedDf[order(cleanedDf$subID),]

# rename the currentTraitIdx.1 column
colnames(cleanedDf)[colnames(cleanedDf)=="currentTraitIdx.1"] <- "currentTrait"
```

set parameters for the loops
```{r}
# initiate an empty dataframe
stimuliDf = data.frame(subID = integer(),
                       runNum = integer(),
                       currentContext = character(),
                       trialInRun = integer(),
                       currentTrial = integer(), 
                       currentOnsetPTime = double(),
                       currentTrait = character())
```



```{r}
# extract subject IDs
subIDs <- unique(cleanedDf$subID)

# loop through each subject
for(id in subIDs){
  
  # subset data for the present subject 
  subDf <- subset(cleanedDf, subID == id)
  
  # extract run numbers
  nRuns <- unique(subDf$runNum)
  
  # loop through each run
  for (run in nRuns){
    
    # extract the index number for the first trial in the run
    idx = which(subDf$runNum == run & subDf$trialInRun == 1)
    
    # extract all trials data in a given run (we have 77 trials in each run)
    runDf = subDf[idx: (idx+76),]
    
    # extract rows that are not for catch trials
    cleanedRunDf <- subset(runDf,is.nan(currentCatch))
    
    # extract relevant columns
    cleanedRunDf <- cleanedRunDf[,c("subID", "runNum", "currentContext", "trialInRun", "currentTrial", "currentOnsetPTime","currentTrait")]
    
    # print out the trialInRun in the last row as a sanity check
    print(tail(cleanedRunDf$trialInRun, 1))
    # append to the stimuli dataframe
    stimuliDf <- rbind(stimuliDf, cleanedRunDf)
  }
   
}
```


```{r}
write.csv(stimuliDf, "stimuliDf.csv", row.names = F)
```

